"""document transaction_identity

Revision ID: 45243245c28d
Revises: 04e9e2f752f0
Create Date: 2026-08-04 17:03:36.677756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45243245c28d'
down_revision: Union[str, Sequence[str], None] = '04e9e2f752f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('transaction_identity', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('transaction_identity_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'transaction_identity_confidence')
    op.drop_column('documents', 'transaction_identity')
    # ### end Alembic commands ###
