"""SQLAlchemy 2.0 declarative models, targeted at PostgreSQL via psycopg v3.

Design constraints these tables exist to satisfy:

1. **Continuous commit.** Every processed document updates the database
   immediately; nothing is deferred to batch end. The app must survive crash,
   shutdown and power loss with no data loss.
2. **Per-stage resume.** Stage state is tracked per *document*, not per batch, so
   a restart never re-runs finished work and never duplicates it.
3. **One CSV row per person.** Stored normalised here; the exporter denormalises.
4. **OCR text is transient.** Purged after 30 days, never backed up. Images are
   never stored - filename, path and metadata only.
5. **Yearly rotation.** Prior year archived to /backup then purged, so every
   large table carries an indexed timestamp to partition on.

Identifier columns (PAN, Aadhaar) are fixed-width **text**, never numeric.
`example.csv` shows what numeric coercion costs: Aadhaars arrived as `6.63E+11`,
irrecoverably.
"""

from __future__ import annotations

import enum
from datetime import date, datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Declarative base with a consistent naming convention.

    Explicit constraint names matter for Alembic: without them, autogenerated
    migrations produce unnamed constraints that later revisions cannot drop.
    """

    metadata = __import__("sqlalchemy").MetaData(naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    })


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class BatchState(str, enum.Enum):
    QUEUED = "queued"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"


class StageState(str, enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"
    SKIPPED = "skipped"


class DocumentState(str, enum.Enum):
    PROCESSING = "processing"
    PROCESSED = "processed"
    FAILED = "failed"
    NEEDS_REVIEW = "needs_review"


class PersonRelation(str, enum.Enum):
    """Matches the CSV's `Transaction Relation (PC)` column exactly."""

    BUYER = "B"
    SELLER = "S"


class BatchMode(str, enum.Enum):
    MANUAL = "manual"
    AUTO = "auto"


def _enum(py_enum: type[enum.Enum], name: str) -> Enum:
    """Native PostgreSQL ENUM, stored by value rather than by Python name."""
    return Enum(py_enum, name=name, native_enum=True,
                values_callable=lambda e: [m.value for m in e])


TS = DateTime(timezone=True)

#: BIGSERIAL on PostgreSQL, plain INTEGER on SQLite. SQLite only auto-increments
#: an `INTEGER PRIMARY KEY` (its rowid alias) - a BIGINT primary key there has no
#: default and inserts fail with a NOT NULL violation. The variant keeps
#: PostgreSQL on 64-bit identifiers while letting the schema be created on SQLite
#: for verification.
BigIntPK = BigInteger().with_variant(Integer, "sqlite")


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    username: Mapped[str] = mapped_column(String(150), unique=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False)

    batches: Mapped[list[Batch]] = relationship(back_populates="user")


class Batch(Base):
    __tablename__ = "batches"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), index=True)

    state: Mapped[BatchState] = mapped_column(
        _enum(BatchState, "batch_state"), default=BatchState.QUEUED, nullable=False)
    #: Position in the queue. At most 4 batches may be queued at once; enforced in
    #: the repository rather than by a constraint so the error can explain itself.
    queue_position: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    file_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_bytes: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)

    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False, index=True)
    started_at: Mapped[datetime | None] = mapped_column(TS)
    finished_at: Mapped[datetime | None] = mapped_column(TS)

    user: Mapped[User | None] = relationship(back_populates="batches")
    documents: Mapped[list[Document]] = relationship(
        back_populates="batch", cascade="all, delete-orphan",
        passive_deletes=True)

    __table_args__ = (
        CheckConstraint("file_count >= 0", name="file_count_non_negative"),
        CheckConstraint("total_bytes >= 0", name="total_bytes_non_negative"),
        Index("ix_batches_state_position", "state", "queue_position"),
    )


class Document(Base):
    """The resume unit. One row per PDF."""

    __tablename__ = "documents"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    batch_id: Mapped[int] = mapped_column(ForeignKey("batches.id", ondelete="CASCADE"),
                                         nullable=False)
    #: Internal handle for this document within its batch. Seeded from the file
    #: name at upload because the row has to exist and be addressable before
    #: anything has been read - it is NOT NULL and unique per batch, and
    #: `add_many` drops an entry without one.
    #:
    #: **This is not the Transaction Identity.** It used to be used as one, so a
    #: deed whose registration number could not be read exported its file name
    #: instead - see `transaction_identity` below and R-043.
    document_id: Mapped[str] = mapped_column(String(100), nullable=False)
    #: The registration number read off the deed itself, e.g.
    #: "BGP-1-00275-2025-26". NULL until extraction finds one, and it stays NULL
    #: when nothing convincing is there: the export must show an empty cell
    #: rather than a value that might belong to a previous owner.
    transaction_identity: Mapped[str | None] = mapped_column(String(100))
    #: How sure the extractor was. Kept so an operator can see why a cell is
    #: blank, and so a low-confidence run can be reviewed rather than trusted.
    transaction_identity_confidence: Mapped[float | None] = mapped_column(Float)
    source_filename: Mapped[str] = mapped_column(String(500), nullable=False)
    #: Path only. Rendered page images are never stored in the database.
    source_path: Mapped[str | None] = mapped_column(String(1000))
    #: The prepared copy: separable overlays removed, text layer guaranteed.
    #: Everything downstream reads this when it is set, so there is one notion
    #: of "the document". The original is never modified and stays the record.
    cleaned_path: Mapped[str | None] = mapped_column(String(1000))
    page_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)

    # Per-stage state is what makes resume possible.
    ocr_state: Mapped[StageState] = mapped_column(
        _enum(StageState, "stage_state"), default=StageState.PENDING, nullable=False)
    extract_state: Mapped[StageState] = mapped_column(
        _enum(StageState, "stage_state"), default=StageState.PENDING, nullable=False)
    translate_state: Mapped[StageState] = mapped_column(
        _enum(StageState, "stage_state"), default=StageState.PENDING, nullable=False)
    validate_state: Mapped[StageState] = mapped_column(
        _enum(StageState, "stage_state"), default=StageState.PENDING, nullable=False)

    #: OCR retries exactly once; extraction retries once. Caps live in config.
    ocr_attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    extract_attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    overall_state: Mapped[DocumentState] = mapped_column(
        _enum(DocumentState, "document_state"),
        default=DocumentState.PROCESSING, nullable=False)
    #: OCR_P / OCR_F, carried into the CSV.
    processing_status: Mapped[str | None] = mapped_column(String(20))
    failure_reason: Mapped[str | None] = mapped_column(Text)

    # -- PDF validation ---------------------------------------------------
    #
    # Written only after a stage has failed. A document that processed cleanly
    # is never validated: the file demonstrably opened, and re-reading it to
    # confirm that would spend I/O on every document to learn nothing.
    #
    # Columns rather than a separate table: these are facts about one document,
    # read on exactly the screens that already load it, so a join buys nothing.

    #: One of `core.pdf_validation.Status`. NULL means "never validated".
    validation_status: Mapped[str | None] = mapped_column(String(32))
    validation_error_code: Mapped[str | None] = mapped_column(String(48))
    validation_error_message: Mapped[str | None] = mapped_column(Text)
    #: Comma-separated 1-based page numbers ("7,8"). Text rather than an array
    #: so the SQLite fallback behaves identically to PostgreSQL.
    corrupted_pages: Mapped[str | None] = mapped_column(String(500))
    validated_at: Mapped[datetime | None] = mapped_column(TS)
    validator_version: Mapped[str | None] = mapped_column(String(16))
    #: Whether another attempt is worth offering. False for a file that cannot
    #: be opened: a retry fails identically and costs another GPU stage.
    is_retryable: Mapped[bool | None] = mapped_column(Boolean)

    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False)
    updated_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 onupdate=func.now(), nullable=False)

    batch: Mapped[Batch] = relationship(back_populates="documents")
    # passive_deletes=True: the FKs declare ON DELETE CASCADE, so the database
    # removes children itself. Without this the ORM also issues its own DELETEs
    # and then warns that fewer rows matched than expected, because the cascade
    # already took them. delete-orphan is retained - it is what makes
    # `doc.persons.clear()` in the repositories actually delete rows.
    ocr_pages: Mapped[list[OcrPage]] = relationship(
        back_populates="document", cascade="all, delete-orphan",
        passive_deletes=True)
    extractions: Mapped[list[Extraction]] = relationship(
        back_populates="document", cascade="all, delete-orphan",
        passive_deletes=True)
    property_: Mapped[Property | None] = relationship(
        back_populates="document", cascade="all, delete-orphan", uselist=False,
        passive_deletes=True)
    persons: Mapped[list[Person]] = relationship(
        back_populates="document", cascade="all, delete-orphan",
        passive_deletes=True)
    validations: Mapped[list[ValidationResult]] = relationship(
        back_populates="document", cascade="all, delete-orphan",
        passive_deletes=True)
    #: Append-only diagnosis history. Ordered oldest first so the sequence
    #: reads the way it happened.
    failure_events: Mapped[list[FailureEvent]] = relationship(
        back_populates="document", cascade="all, delete-orphan",
        passive_deletes=True, order_by="FailureEvent.created_at")

    __table_args__ = (
        # A document number must be unique within its batch: this is the guard
        # against duplicate processing after a crash and restart.
        UniqueConstraint("batch_id", "document_id", name="batch_document"),
        Index("ix_documents_batch_overall", "batch_id", "overall_state"),
        # Drives the resume scan on startup.
        Index("ix_documents_resume", "batch_id", "ocr_state", "extract_state",
              "translate_state"),
    )


class OcrPage(Base):
    """Cleaned OCR text, one row per page. Transient - purged after 30 days."""

    __tablename__ = "ocr_pages"

    id: Mapped[int] = mapped_column(BigIntPK, primary_key=True)
    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    page_number: Mapped[int] = mapped_column(Integer, nullable=False)
    #: LF line endings only. CRLF changes tokenisation - see ADR-005.
    text: Mapped[str] = mapped_column(Text, nullable=False)
    char_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    #: Indexed because the 30-day expiry sweep filters on it.
    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False, index=True)

    document: Mapped[Document] = relationship(back_populates="ocr_pages")

    __table_args__ = (
        UniqueConstraint("document_id", "page_number", name="document_page"),
    )


class Extraction(Base):
    """Raw model output plus accounting. Retained for audit."""

    __tablename__ = "extractions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True)
    attempt: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    raw_output: Mapped[str | None] = mapped_column(Text)
    parsed_ok: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    #: Retry trigger, threshold 0.6.
    pan_coverage: Mapped[float | None] = mapped_column(Numeric(4, 3))
    prompt_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    completion_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    #: Hit the token ceiling. On this workload that usually means a repetition
    #: loop, not a long answer, so it is treated as a validation failure.
    truncated: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    model_name: Mapped[str | None] = mapped_column(String(200))
    #: Recorded per extraction because it affects accuracy. Q4_K_M produced a 10x
    #: error on a sale consideration where BF16 was correct; results must be
    #: attributable to a precision.
    quantisation: Mapped[str | None] = mapped_column(String(40))
    prompt_name: Mapped[str | None] = mapped_column(String(100))
    duration_s: Mapped[float | None] = mapped_column(Numeric(10, 3))
    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False)

    document: Mapped[Document] = relationship(back_populates="extractions")

    __table_args__ = (
        UniqueConstraint("document_id", "attempt", name="document_attempt"),
    )


class Property(Base):
    __tablename__ = "properties"

    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True)

    schedule_c_address: Mapped[str | None] = mapped_column(Text)
    address_translated: Mapped[str | None] = mapped_column(Text)
    state: Mapped[str | None] = mapped_column(String(100))
    postal_code: Mapped[str | None] = mapped_column(String(10))

    sale_consideration: Mapped[int | None] = mapped_column(Numeric(15, 0))
    registration_fee: Mapped[int | None] = mapped_column(Numeric(15, 0))
    #: Passthrough. The formula is undefined and example.csv contradicts the
    #: written spec, so nothing is computed here. See ADR-010.
    stamp_value: Mapped[int | None] = mapped_column(Numeric(15, 0))
    paid_in_cash: Mapped[bool | None] = mapped_column(Boolean)

    transaction_date: Mapped[date | None] = mapped_column(Date)
    registration_office: Mapped[str | None] = mapped_column(String(300))

    document: Mapped[Document] = relationship(back_populates="property_")


class Person(Base):
    __tablename__ = "persons"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    relation: Mapped[PersonRelation] = mapped_column(
        _enum(PersonRelation, "person_relation"), nullable=False)
    #: Stable ordering so CSV rows are reproducible across exports.
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)

    name: Mapped[str | None] = mapped_column(String(500))
    #: Names are transliterated, addresses translated - different operations.
    name_translated: Mapped[str | None] = mapped_column(String(500))
    gender: Mapped[str | None] = mapped_column(String(20))
    father_name: Mapped[str | None] = mapped_column(String(500))
    father_name_translated: Mapped[str | None] = mapped_column(String(500))

    #: Fixed-width TEXT, never numeric. Numeric coercion destroyed the Aadhaars
    #: in example.csv (they arrived as 6.63E+11).
    aadhaar_number: Mapped[str | None] = mapped_column(String(12))
    pan_card_number: Mapped[str | None] = mapped_column(String(10))

    address: Mapped[str | None] = mapped_column(Text)
    address_translated: Mapped[str | None] = mapped_column(Text)
    state: Mapped[str | None] = mapped_column(String(100))
    postal_code: Mapped[str | None] = mapped_column(String(10))

    confidence: Mapped[float | None] = mapped_column(Numeric(4, 3))
    remarks: Mapped[str | None] = mapped_column(String(500))

    document: Mapped[Document] = relationship(back_populates="persons")

    __table_args__ = (
        UniqueConstraint("document_id", "relation", "ordinal",
                         name="document_relation_ordinal"),
        # length() rather than char_length(): identical on PostgreSQL for text,
        # but char_length() does not exist in SQLite, and keeping the schema
        # creatable there is what allows the repository logic to be verified
        # without a PostgreSQL server. PostgreSQL remains the production target.
        CheckConstraint("aadhaar_number IS NULL OR length(aadhaar_number) = 12",
                        name="aadhaar_twelve_digits"),
        CheckConstraint("pan_card_number IS NULL OR length(pan_card_number) = 10",
                        name="pan_ten_chars"),
        Index("ix_persons_pan", "pan_card_number"),
    )


class ValidationResult(Base):
    """One flag occurrence. The two CSV remarks columns are assembled from here."""

    __tablename__ = "validation_results"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True)
    #: NULL for document-level findings (CSV column 15); set for person-level
    #: findings (column 42).
    person_id: Mapped[int | None] = mapped_column(
        ForeignKey("persons.id", ondelete="CASCADE"))

    flag_code: Mapped[str] = mapped_column(String(12), nullable=False)
    field: Mapped[str | None] = mapped_column(String(80))
    detail: Mapped[str | None] = mapped_column(Text)
    confidence: Mapped[float | None] = mapped_column(Numeric(4, 3))
    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False)

    document: Mapped[Document] = relationship(back_populates="validations")

    __table_args__ = (
        Index("ix_validation_document_flag", "document_id", "flag_code"),
    )


class Setting(Base):
    """Key-value settings mirroring the Settings page. `.env` overrides these."""

    __tablename__ = "settings"

    key: Mapped[str] = mapped_column(String(120), primary_key=True)
    value: Mapped[str | None] = mapped_column(Text)
    updated_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 onupdate=func.now(), nullable=False)


class LogEntry(Base):
    """Structured log. Written only when DEBUG is enabled."""

    __tablename__ = "logs"

    id: Mapped[int] = mapped_column(BigIntPK, primary_key=True)
    level: Mapped[str] = mapped_column(String(12), nullable=False)
    logger: Mapped[str | None] = mapped_column(String(120))
    message: Mapped[str] = mapped_column(Text, nullable=False)
    batch_id: Mapped[int | None] = mapped_column(ForeignKey("batches.id",
                                                            ondelete="SET NULL"))
    document_id: Mapped[int | None] = mapped_column(ForeignKey("documents.id",
                                                               ondelete="SET NULL"))
    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False, index=True)

    __table_args__ = (
        Index("ix_logs_level_created", "level", "created_at"),
    )


class FailureEvent(Base):
    """One diagnosis, appended - never updated, never overwritten.

    A retry used to erase the previous verdict: `requeue_ocr` clears
    `failure_reason`, so a document that failed three different ways showed only
    the last one, and the sequence that would explain it was gone. That sequence
    is often the whole story - "watermark removal failed, then OCR found no
    text" is a different problem from "OCR found no text" on its own.

    Append-only, so the history survives every retry. The document keeps its
    current verdict in its own columns for the common case; this table answers
    "what happened to it over time".
    """

    __tablename__ = "failure_events"

    id: Mapped[int] = mapped_column(BigIntPK, primary_key=True)
    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    #: The batch is denormalised so a batch-wide failure report needs no join
    #: through documents, and survives as SET NULL if the batch is removed.
    batch_id: Mapped[int | None] = mapped_column(
        ForeignKey("batches.id", ondelete="SET NULL"))

    #: Which stage produced it: ocr, extract, translate, validate, watermark.
    stage: Mapped[str] = mapped_column(String(24), nullable=False)
    #: A `core.failure_codes` code - stable, so logs and exports keep working
    #: when the wording changes.
    code: Mapped[str] = mapped_column(String(48), nullable=False)
    #: What the operator is told.
    message: Mapped[str | None] = mapped_column(Text)
    #: The exception text, kept for whoever debugs it and never shown by
    #: default. Sanitised before it gets here - no stack traces.
    technical: Mapped[str | None] = mapped_column(Text)
    #: Which attempt this was, so a repeated identical failure is visible as
    #: repetition rather than looking like one event.
    attempt: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    retryable: Mapped[bool | None] = mapped_column(Boolean)

    created_at: Mapped[datetime] = mapped_column(TS, server_default=func.now(),
                                                 nullable=False)

    document: Mapped[Document] = relationship(back_populates="failure_events")

    __table_args__ = (
        # The history of one document, in order - the only query this serves.
        Index("ix_failure_events_document", "document_id", "created_at"),
        Index("ix_failure_events_batch_code", "batch_id", "code"),
    )
